languageCode = "en"
languageName = "English"
weight = 1

title = "Dr Jonathan Paul Mitchell"

[params]
  isoCode = "en"
  displayName = "EN"
  rtl = false

dateFormat = "2 January 2006"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[author]
  name = "Jonathan Paul Mitchell"
  image = "img/author.jpg"
  # headline = "I'm only human"
  # bio = "A little bit about you"
  links = [
    { email = "mailto:hello@jonathanmitchell.me" },
  #   { link = "https://link-to-some-website.com/" },
  #   { discord = "https://discord.gg/invitecode" },
    { github = "https://github.com/UncouthRegions" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #  { mastodon = "https://zirk.us/@jpmitchell" },
  #   { medium = "https://medium.com/username" },
    { orcid = "https://orcid.org/0000-0003-4107-7453" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
    { researchgate = "https://www.researchgate.net/profile/Jonathan-Mitchell-4" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { telegram = "https://t.me/username" },
    { twitter = "https://twitter.com/UncouthRegions" },
  #   { whatsapp = "https://wa.me/phone-number" },
  ]
