baseURL = "https://www.jonathanpaulmitchell.com/"
languageCode = "en-gb"
theme = "archie"
title = "Dr Jonathan Paul Mitchell"
# copyright = "© Dr J. P. Mitchell"
paginate = 5 # articles per page
dateFormat = "January 2, 2006"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
    customcss=["css/mods.css"]
    mode="toggle" # color-mode → light, dark, toggle, or auto
    useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
    title = "Dr Jonathan Paul Mitchell"
    description = "Jonathan Paul Mitchell's academic homepage"
    # subtitle = "The Website of Dr Jonathan Paul Mitchell"
    author = "Jonathan"

    # Main menu Items

    [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.main]]
    name = "Updates"
    url = "/posts"
    weight = 2

    # [[menu.main]]
    # name = "About Me"
    # url = "/about"
    # weight = 3

    [[menu.main]]
    name = "Curriculum Vitae"
    url = "/cv"
    weight = 3

    # Social Tags
    [[Params.Social]]
    name = "GitHub"
    icon = "github"
    url = "https://github.com/uncouthregions/"

    [[Params.Social]]
    name = "Twitter"
    icon = "twitter"
    url = "https://twitter.com/UncouthRegions/"
