baseURL = "http://jonathanpaulmitchell.com"
languageCode = "en-gb"
title = "Dr Jonathan Paul Mitchell"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the lee.so; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# ------------------------------
theme = "hugo-paper"
title = "Paper"

[params]
  color = 'linen'

  twitter = 'UncouthRegions'
 # github = 'nanxiaobei'
 # instagram = 'nan.xiaobei'

  bio = 'Discover fresh context'
  author = "Jonathan Paul Mitchell"
  description = "Personal website powered by Hugo"
 
 
 

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "Me"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Papers etc."
    weight = 3

[[menu.main]]
    url = "/cv/"
    name = "C.V."
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:hello@jonathanpaulmitchell.com"
    name = "fas fa-envelope"
    weight = 1

#[[menu.icon]]
 #   url = "https://github.com/username/"
  #  name = "fab fa-github"
   # weight = 2

[[menu.icon]]
    url = "https://twitter.com/UncouthRegions/"
    name = "fab fa-twitter"
    weight = 3

# [[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
 #   name = "fab fa-linkedin"
  #  weight = 4

#[[menu.icon]]
 #   url = "https://www.stackoverflow.com/username/"
  #  name = "fab fa-stack-overflow"
   # weight = 5






[params]
  

# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true