[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.83.1"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"