# netlify.toml

[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.16"
  TZ = "GMT"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.100.2"
  HUGO_ENV = "production"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.100.2"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"